.TH PROMPT 1 "Jul 12, 2008" "" ""
.\"
.\" Man page written by Kasper Peeters <kasper.peeters@aei.mpg.de>
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
prompt \- give any program command-line editing facilities
.SH SYNOPSIS
.BR "prompt"
.SH DESCRIPTION
.B prompt
is a simple wrapper which provides command-line editing for programs 
that do not have it.

Not all programs with a command line interface provide an input
history or even the ability to use the cursor keys to change the
input. The prompt program wraps any program, intercepting stdin,
stdout and stderr and providing the user with such editing facilities.

.SH SEE ALSO
.BR modglue (1).
.BR ptywrap (1).

See the web page at
.BR "http://www.aei.mpg.de/~peekas/modglue/"
for more information.
.SH AUTHORS
Kasper Peeters <kasper.peeters@aei.mpg.de>

